name = "gauth"
version = "1.0.0"

description = "A modular first authentication base"
licences = ["Apache-2.0"]
repository = { type = "github", user = "BradBot1", repo = "gleam_gauth" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
