name: Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  erlang:
    runs-on: ubuntu-latest
    name: Erlang
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam test --target erlang
      - run: gleam format --check src test
  node:
    runs-on: ubuntu-latest
    name: NodeJS
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: gleam deps download
      - run: gleam test --target javascript --runtime node
  deno:
    runs-on: ubuntu-latest
    name: DenoJS
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: gleam deps download
      - run: gleam test --target javascript --runtime deno -- --allow-all
  bun:
    runs-on: ubuntu-latest
    name: BunJS
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: gleam deps download
      - run: gleam test --target javascript --runtime bun
