name: Testing

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  erlang:
    runs-on: ubuntu-latest
    name: Erlang
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
  node:
    runs-on: ubuntu-latest
    name: NodeJS
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.5.1"
          rebar3-version: "3"
          elixir-version: "1.15.4"
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: gleam deps download
      - run: gleam test --target javascript